//
//  Constant.swift
//  PassportNFCProfessional
//
//  Created by honorsupplying on 3/10/25.
//

import Foundation

public class Constant {
    
    static let nationality:[String:String] = [
        "AND": "Andorran",
        "ARE": "Emirati",
        "AFG": "Afghan",
        "ATG": "Antiguan, Barbudan",
        "AIA": "Anguillian",
        "ALB": "Albanian",
        "ARM": "Armenian",
        "ANT": "Dutch",
        "AGO": "Angolan",
        "ATA": "Antarctica",
        "ARG": "Argentinean",
        "ASM": "American Samoan",
        "AUT": "Austrian",
        "AUS": "Australian",
        "ABW": "Aruban",
        "ALA": "Swedish",
        "AZE": "Azerbaijani",
        "BIH": "Bosnian, Herzegovinian",
        "BRB": "Barbadian",
        "BGD": "Bangladeshi",
        "BEL": "Belgian",
        "BFA": "Burkinabe",
        "BGR": "Bulgarian",
        "BHR": "Bahraini",
        "BDI": "Burundian",
        "BEN": "Beninese",
        "BLM": "Saint Barthélemy Islander",
        "BMU": "Bermudian",
        "BRN": "Bruneian",
        "BOL": "Bolivian",
        "BES": "Dutch",
        "BRA": "Brazilian",
        "BHS": "Bahamian",
        "BTN": "Bhutanese",
        "BVT": "Bouvet Island",
        "BWA": "Motswana",
        "BLR": "Belarusian",
        "BLZ": "Belizean",
        "CAN": "Canadian",
        "CCK": "Cocos Islander",
        "COD": "Congolese",
        "CAF": "Central African",
        "COG": "Congolese",
        "CHE": "Swiss",
        "CIV": "Ivorian",
        "COK": "Cook Islander",
        "CHL": "Chilean",
        "CMR": "Cameroonian",
        "CHN": "Chinese",
        "COL": "Colombian",
        "CRI": "Costa Rican",
        "SCG": "Montenegrins, Serbs",
        "CTE": "Canton and Enderbury Islands",
        "CUB": "Cuban",
        "CPV": "Cape Verdian",
        "CUW": "Curaçaoan",
        "CXR": "Christmas Island",
        "CYP": "Cypriot",
        "CZE": "Czech",
        "DEU": "German",
        "DJI": "Djibouti",
        "DNK": "Danish",
        "DMA": "Dominican",
        "DOM": "Dominican",
        "DZA": "Algerian",
        "ECU": "Ecuadorean",
        "EST": "Estonian",
        "EGY": "Egyptian",
        "ESH": "Sahrawi",
        "ERI": "Eritrean",
        "ESP": "Spanish",
        "ETH": "Ethiopian",
        "FIN": "Finnish",
        "FJI": "Fijian",
        "FLK": "Falkland Islander",
        "FSM": "Micronesian",
        "FRO": "Faroese",
        "ATF": "French",
        "FRA": "French",
        "FXX": "Metropolitan France",
        "GAB": "Gabonese",
        "GBR": "British",
        "GRD": "Grenadian",
        "GEO": "Georgian",
        "GUF": "French Guiana",
        "GGY": "Channel Islander",
        "GHA": "Ghanaian",
        "GIB": "Gibraltar",
        "GRL": "Greenlandic",
        "GMB": "Gambian",
        "GIN": "Guinean",
        "GLP": "Guadeloupian",
        "GNQ": "Equatorial Guinean",
        "GRC": "Greek",
        "SGS": "South Georgia and the South Sandwich Islander",
        "GTM": "Guatemalan",
        "GUM": "Guamanian",
        "GNB": "Guinea-Bissauan",
        "GUY": "Guyanese",
        "HKG": "Chinese",
        "HMD": "Heard and McDonald Islander",
        "HND": "Honduran",
        "HRV": "Croatian",
        "HTI": "Haitian",
        "HUN": "Hungarian",
        "IDN": "Indonesian",
        "IRL": "Irish",
        "ISR": "Israeli",
        "IMN": "Manx",
        "IND": "Indian",
        "IOT": "Indian",
        "IRQ": "Iraqi",
        "IRN": "Iranian",
        "ISL": "Icelander",
        "ITA": "Italian",
        "JEY": "Channel Islander",
        "JAM": "Jamaican",
        "JOR": "Jordanian",
        "JPN": "Japanese",
        "JTN": "Johnston Island",
        "KEN": "Kenyan",
        "KGZ": "Kirghiz",
        "KHM": "Cambodian",
        "KIR": "I-Kiribati",
        "COM": "Comoran",
        "KNA": "Kittian and Nevisian",
        "PRK": "North Korean",
        "KOR": "South Korean",
        "KWT": "Kuwaiti",
        "CYM": "Caymanian",
        "KAZ": "Kazakhstani",
        "LAO": "Laotian",
        "LBN": "Lebanese",
        "LCA": "Saint Lucian",
        "LIE": "Liechtensteiner",
        "LKA": "Sri Lankan",
        "LBR": "Liberian",
        "LSO": "Mosotho",
        "LTU": "Lithuanian",
        "LUX": "Luxembourger",
        "LVA": "Latvian",
        "LBY": "Libyan",
        "MAR": "Moroccan",
        "MCO": "Monegasque",
        "MDA": "Moldovan",
        "MNE": "Montenegrin",
        "MAF": "Saint Martin Islander",
        "MDG": "Malagasy",
        "MHL": "Marshallese",
        "MID": "Midway Islands",
        "MKD": "Macedonian",
        "MLI": "Malian",
        "MMR": "Myanmar",
        "MNG": "Mongolian",
        "MAC": "Chinese",
        "MNP": "American",
        "MTQ": "French",
        "MRT": "Mauritanian",
        "MSR": "Montserratian",
        "MLT": "Maltese",
        "MUS": "Mauritian",
        "MDV": "Maldivan",
        "MWI": "Malawian",
        "MEX": "Mexican",
        "MYS": "Malaysian",
        "MOZ": "Mozambican",
        "NAM": "Namibian",
        "NCL": "New Caledonian",
        "NER": "Nigerian",
        "NFK": "Norfolk Islander",
        "NGA": "Nigerian",
        "NIC": "Nicaraguan",
        "NLD": "Dutch",
        "NOR": "Norwegian",
        "NPL": "Nepalese",
        "ATN": "Dronning Maud Land",
        "NRU": "Nauruan",
        "NTZ": "Neutral Zone",
        "NIU": "Niuean",
        "NZL": "New Zealander",
        "OMN": "Omani",
        "PAN": "Panamanian",
        "PCI": "Pacific Islands Trust Territory",
        "PER": "Peruvian",
        "PYF": "French Polynesian",
        "PNG": "Papua New Guinean",
        "PHL": "Filipino",
        "PAK": "Pakistani",
        "POL": "Polish",
        "SPM": "French",
        "PCN": "Pitcairn Islander",
        "PRI": "Puerto Rican",
        "PSE": "Palestinian",
        "PRT": "Portuguese",
        "PUS": "U.S. Miscellaneous Pacific Islands",
        "PLW": "Palauan",
        "PRY": "Paraguayan",
        "PCZ": "Panama Canal Zone",
        "QAT": "Qatari",
        "REU": "French",
        "ROU": "Romanian",
        "SRB": "Serbian",
        "RUS": "Russian",
        "RWA": "Rwandan",
        "SAU": "Saudi Arabian",
        "SLB": "Solomon Islander",
        "SYC": "Seychellois",
        "SDN": "Sudanese",
        "SWE": "Swedish",
        "SGP": "Singaporean",
        "SHN": "Saint Helenian",
        "SVN": "Slovene",
        "SJM": "Norwegian",
        "SVK": "Slovak",
        "SLE": "Sierra Leonean",
        "SMR": "Sammarinese",
        "SEN": "Senegalese",
        "SOM": "Somali",
        "SUR": "Surinamer",
        "STP": "Sao Tomean",
        "SLV": "Salvadoran",
        "SYR": "Syrian",
        "SWZ": "Swazi",
        "TCA": "Turks and Caicos Islander",
        "TCD": "Chadian",
        "TGO": "Togolese",
        "THA": "Thai",
        "TJK": "Tadzhik",
        "TKL": "Tokelauan",
        "TLS": "East Timorese",
        "TKM": "Turkmen",
        "TUN": "Tunisian",
        "TON": "Tongan",
        "TUR": "Turkish",
        "TTO": "Trinidadian",
        "TUV": "Tuvaluan",
        "TWN": "Taiwanese",
        "TZA": "Tanzanian",
        "UKR": "Ukrainian",
        "UGA": "Ugandan",
        "UMI": "American",
        "USA": "American",
        "URY": "Uruguayan",
        "UZB": "Uzbekistani",
        "VAT": "Italian",
        "VCT": "Saint Vincentian",
        "VDR": "North Vietnam",
        "VEN": "Venezuelan",
        "VGB": "Virgin Islander",
        "VIR": "Virgin Islander",
        "VNM": "Vietnamese",
        "VUT": "Ni-Vanuatu",
        "WLF": "Wallis and Futuna Islander",
        "WAK": "Wake Island",
        "WSM": "Samoan",
        "YEM": "Yemeni",
        "MYT": "French",
        "ZAF": "South African",
        "ZMB": "Zambian",
        "ZWE": "Zimbabwean"
    ]
    
    static let country:[String:String] = [
        "AFG": "AFGHANISTAN",
        "ALB": "ALBANIA",
        "DZA": "ALGERIA",
        "ASM": "AMERICAN SAMOA",
        "AND": "ANDORRA",
        "AGO": "ANGOLA",
        "AIA": "ANGUILLA",
        "ATA": "ANTARCTICA",
        "ATG": "ANTIGUA AND BARBUDA",
        "ARG": "ARGENTINA",
        "ARM": "ARMENIA",
        "ABW": "ARUBA",
        "AUS": "AUSTRALIA",
        "AUT": "AUSTRIA",
        "AZE": "AZERBAIJAN",
        "BHS": "BAHAMAS",
        "BHR": "BAHRAIN",
        "BGD": "BANGLADESH, PEOPLES REPUBLIC OF",
        "BRB": "BARBADOS",
        "BLR": "BELARUS",
        "BYS": "BELARUSSIAN SSR",
        "BEL": "BELGIUM",
        "BLZ": "BELIZE",
        "BEN": "BENIN",
        "BMU": "BERMUDA",
        "BTN": "BHUTAN",
        "BOL": "BOLIVIA",
        "BIH": "BOSNIA HERZEGGOVINA",
        "BWA": "BOTSWANA",
        "BVT": "BOUVET ISLAND",
        "BRA": "BRAZIL",
        "GBD": "BRITISH DEPENDENT TERRITORIES",
        "IOT": "BRITISH INDIAN OCEAN TERRITORY",
        "GBN": "BRITISH NATIONAL",
        "GBO": "BRITISH OVERSEAS CITIZEN",
        "GBP": "BRITISH PROTECTED PERSON",
        "GBS": "BRITISH SUBJECT",
        "VGB": "BRITISH VIRGIN ISLANDS",
        "BRN": "BRUNEI",
        "BGR": "BULGARIA",
        "BFA": "BURKINA FASO",
        "BDI": "BURUNDI",
        "KHM": "CAMBODIA",
        "CMR": "CAMEROON, UNITED REPUBLIC OF",
        "CAN": "CANADA",
        "CTE": "CANTON AND ENDERBURY ISLANDS",
        "CPV": "CAPE VERDE",
        "CYM": "CAYMAN ISLANDS",
        "CAF": "CENTRAL AFRICAN REPUBLIC",
        "TCD": "CHAD",
        "CHL": "CHILE",
        "CHN": "CHINA",
        "CXR": "CHRISTMAS ISLAND",
        "CCK": "COCOS (KEELING) ISLANDS",
        "COL": "COLOMBIA",
        "COM": "COMOROS",
        "COD": "CONGO DEMOCRATIC REPUBLIC",
        "COG": "CONGO REPUBLIC OF",
        "COK": "COOK ISLANDS",
        "CRI": "COSTA RICA",
        "CIV": "COTE D'IVOIRE IVORY COAST",
        "HRV": "CROATIA, REPUBLIC OF",
        "CUB": "CUBA",
        "CYP": "CYPRUS",
        "CZE": "CZECH REPUBLIC",
        "DNK": "DENMARK",
        "DJI": "DJIBOUTI",
        "DMA": "DOMINICA, COMMONWEALTH OF",
        "DOM": "DOMINICAN REPUBLIC",
        "ATN": "DRONNING MAUD LAND",
        "TMP": "EAST TIMOR",
        "ECU": "ECUADOR",
        "EGY": "EGYPT",
        "SLV": "EL SALVADOR",
        "ENG": "ENGLAND",
        "GNQ": "EQUITORIAL GUINEA, REPUBLIC OF",
        "ERI": "ERITREA",
        "EST": "ESTONIA",
        "ETH": "ETHIOPIA",
        "FRO": "FAEROE ISLANDS",
        "FLK": "FALKLAND ISLANDS",
        "FJI": "FIJI",
        "FIN": "FINLAND",
        "FRA": "FRANCE",
        "FXX": "FRANCE, METROPOLITAN",
        "GUF": "FRENCH GUIANA",
        "PYF": "FRENCH POLYNESIA",
        "ATF": "FRENCH SOUTH TERRITORY",
        "GAB": "GABON",
        "GMB": "GAMBIA",
        "SGS": "GEORGIA/SANDWICH ISLANDS",
        "GEO": "GEORGIA, REPUBLIC OF",
        "DDR": "GERMAN DEMOCRATIC REPUBLIC",
        "DEU": "GERMANY, FEDERAL REPUBLIC OF",
        "GHA": "GHANA",
        "GIB": "GIBRALTAR",
        "GRC": "GREECE",
        "GRL": "GREENLAND",
        "GRD": "GRENADA",
        "GLP": "GUADELOUPE",
        "GUM": "GUAM",
        "GTM": "GUATEMALA",
        "GIN": "GUINEA",
        "GNB": "GUINEA-BISSAU",
        "GUY": "GUYANA",
        "HTI": "HAITI",
        "HMD": "HEARD AND MCDONALD ISLANDS",
        "HND": "HONDURAS",
        "HKG": "HONG KONG",
        "BDT": "HONG KONG",
        "HUN": "HUNGARY",
        "ISL": "ICELAND",
        "IND": "INDIA",
        "IDN": "INDONESIA",
        "IRN": "IRAN",
        "IRQ": "IRAQ",
        "IRL": "IRELAND",
        "ISR": "ISRAEL",
        "ITA": "ITALY",
        "JAM": "JAMAICA",
        "JPN": "JAPAN",
        "JOR": "JORDAN",
        "KAZ": "KAZAKHSTAN, REPUBLIC OF",
        "KEN": "KENYA",
        "KIR": "KIRIBATI",
        "PRK": "KOREA DEMOCRATIC PEOPLES REPUB",
        "KOR": "KOREA, REPUBLIC OF",
        "KWT": "KUWAIT",
        "KGZ": "KYRGYZSTAN, REPUBLIC OF",
        "LAO": "LAO PEOPLE'S DEMOCRATIC",
        "LVA": "LATVIA, REPUBLIC OF",
        "LBN": "LEBANON",
        "LSO": "LESOTHO",
        "LBR": "LIBERIA",
        "LBY": "LIBYAN ARAB JAMAHIRIYA",
        "LIE": "LIECHTENSTEIN",
        "LTU": "LITHUANIA, REPUBLIC OF",
        "LUX": "LUXEMBOURG",
        "MAC": "MACAU",
        "MKD": "MACEDONIA",
        "MDG": "MADAGASCAR",
        "MWI": "MALAWI",
        "MYS": "MALAYSIA",
        "MDV": "MALDIVES, REPUBLIC OF",
        "MLI": "MALI",
        "MLT": "MALTA",
        "MHL": "MARSHALL ISLANDS REPUBLIC OF",
        "MTQ": "MARTINIQUE",
        "MRT": "MAURITANIA",
        "MUS": "MAURITIUS",
        "MYT": "MAYOTTE, TERRITORIAL COLL OF",
        "MEX": "MEXICO",
        "FSM": "MICRONESIA FEDERATED STATES OF",
        "MDA": "MOLDOVA, REPUBLIC OF",
        "MCO": "MONACO",
        "MNG": "MONGOLIA",
        "MSR": "MONTSERRAT",
        "MAR": "MOROCCO",
        "MOZ": "MOZAMBIQUE",
        "MMR": "MYANMAR",
        "NAM": "NAMIBIA",
        "NRU": "NAURU",
        "NPL": "NEPAL",
        "NLD": "NETHERLANDS",
        "ANT": "NETHERLANDS ANTILLES",
        "NTZ": "NEUTRAL ZONE",
        "NCL": "NEW CALEDONIA",
        "NZL": "NEW ZEALAND",
        "NIC": "NICARAGUA",
        "NER": "NIGER",
        "NGA": "NIGERIA",
        "NIU": "NIUE",
        "NFK": "NORFOLK ISLAND",
        "MNP": "NORTHERN MARIANAS",
        "NOR": "NORWAY",
        "OMN": "OMAN",
        "PAK": "PAKISTAN",
        "PLW": "PALAU, REPUBLIC OF",
        "PSE": "PALESTINIAN AUTHORITY",
        "PAN": "PANAMA",
        "PNG": "PAPUA NUI GUINI",
        "PRY": "PARAGUAY",
        "PER": "PERU",
        "PHL": "PHILIPPINES",
        "PCN": "PITCAIRN ISLAND",
        "POL": "POLAND",
        "PRT": "PORTUGAL",
        "PRI": "PUERTO RICO",
        "QAT": "QATAR",
        "XXC": "REFUGEE OTHERS",
        "XXB": "REFUGEE STATUS",
        "REU": "REUNION",
        "ROM": "ROMANIA",
        "RUS": "RUSSIAN FEDERATION",
        "RWA": "RWANDA",
        "WSM": "SAMOA",
        "SMR": "SAN MARINO",
        "STP": "SAO TOME AND PRINCIPE",
        "SAU": "SAUDI ARABIA",
        "SCO": "SCOTLAND",
        "SEN": "SENEGAL",
        "SYC": "SEYCHELLES",
        "SLE": "SIERRA LEONE",
        "SGP": "SINGAPORE",
        "SVK": "SLOVAK REPUBLIC",
        "SVN": "SLOVENIA",
        "SLB": "SOLOMON ISLANDS",
        "SOM": "SOMALIA",
        "ZAF": "SOUTH AFRICA",
        "ESP": "SPAIN",
        "LKA": "SRI LANKA",
        "SHN": "ST HELENA",
        "KNA": "ST KITTS NEVIS ANGUILLA",
        "LCA": "ST LUCIA",
        "SPM": "ST PIERRE AND MIQUELON",
        "VCT": "ST VINCENT AND THE GRENADINES",
        "XXA": "STATELESS PERSON",
        "SDN": "SUDAN",
        "SUR": "SURINAME",
        "SJM": "SVALBARD AND JAN MAYEN ISLANDS",
        "SWZ": "SWAZILAND",
        "SWE": "SWEDEN",
        "CHE": "SWITZERLAND",
        "SYR": "SYRIAN ARAB REPUBLIC",
        "TWN": "TAIWAN",
        "TJK": "TAJIKISTAN REPUBLIC",
        "TZA": "TANZANIA, UNITED REPUBLIC OF",
        "THA": "THAILAND",
        "TGO": "TOGO",
        "TKL": "TOKELAU",
        "TON": "TONGA",
        "TTO": "TRINIDAD AND TOBAGO",
        "TUN": "TUNISIA",
        "TUR": "TURKEY",
        "TKM": "TURKMENISTAN",
        "TCA": "TURKS AND CAICOS ISLANDS",
        "TUV": "TUVALU",
        "UGA": "UGANDA",
        "UKR": "UKRAINIAN SSR",
        "ARE": "UNITED ARAB EMIRATES",
        "GBR": "UNITED KINGDOM",
        "UNA": "UNITED NATIONS AGENCY",
        "UNO": "UNITED NATIONS ORGANISATION",
        "USA": "UNITED STATES OF AMERICA",
        "VIR": "UNITED STATES VIRGIN ISLANDS",
        "XXX": "UNSPECIFIED NATIONALITY",
        "URY": "URUGUAY",
        "UMI": "US MINOR ISLANDS",
        "UZB": "UZBEKISTAN, REPUBLIC OF",
        "VUT": "VANUATU ACTIVE 09 JAN 2005",
        "VAT": "VATICAN CITY STATE (HOLY SEE)",
        "VEN": "VENEZUELA",
        "VNM": "VIETNAM",
        "WAL": "WALES",
        "WLF": "WALLIS AND FUTUNA ISLANDS",
        "ESH": "WESTERN SAHARA",
        "YEM": "YEMEN",
        "YMD": "YEMEN, DEMOCRATIC",
        "YUG": "YUGOSLAVIA",
        "ZAR": "ZAIRE",
        "ZMB": "ZAMBIA",
        "ZWE": "ZIMBABWE"
    ]
    
    
    public static func getCountryFromCode(countryCode code:String)->String{
        return country[code] ?? "";
    }
    
    public static func getNatiolityFromCode(countryCode code:String)->String{
        return nationality[code] ?? "";
    }
    
}
